# Mandatory properties

# allows you to define the hmac secret from a helm secret
# if not specified its generated on the fly
hmacToken: ""

# docker registry host name such as: gcr.io, docker.io
dockerRegistry: ""

# the cloud project ID if using Google Cloud
projectId: ""

# the user/organisation/group of images in the docker registry - appended to the docker registry host in docker image names
dockerRegistryOrg: ""



# Optional Properties

# the build pack used for the pipeline
buildPackURL: ""
buildPackRef: ""

# the webhook URL to expose this service
webhookUrl: ""

# lets only watch the local namespace for tekton and avoid the tekton webhook component
tekton:
  webhook:
    enabled: false
  rbac:
    cluster: false

# the git source repository of the environment used for GitOps promotion
source:
  owner: ""
  repo: ""
  serverUrl: "https://github.com"
  gitKind: "github"
  user: ""
  token: ""

image:
  repository: gcr.io/jenkinsxio/builder-maven
  tag: 0.1.761
imagePullPolicy: IfNotPresent
terminationGracePeriodSeconds: 180
probe:
  livenessPath: /health
  readinessPath: /ready
command:
- jx
args:
- "controller"
- "environment"
- "-b"
resources:
  limits:
   cpu: 400m
   memory: 256Mi
  requests:
   cpu: 200m
   memory: 128Mi
service:
  name: environment-controller
  type: LoadBalancer
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"

env:
  GIT_AUTHOR_NAME: "jenkins-x-bot"
  GIT_AUTHOR_EMAIL: "jenkins-x@googlegroups.com"
  XDG_CONFIG_HOME: "/home/jenkins"
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
